#!/bin/bash
cp /opt/lets-get-serial/share/applications/lets-get-serial.desktop /usr/share/applications/lets-get-serial.desktop
cp /opt/lets-get-serial/share/icons/hicolor/256x256/apps/lets-get-serial.png /usr/share/icons/hicolor/256x256/apps/lets-get-serial.png
chmod 777 /opt/lets-get-serial/bin/lets-get-serial.sh
